import Head from 'next/head'
import Image from 'next/image'
import Login from '../components/Login'


export default function Home() {
  return (
    <div >
      <Head>
        <title>C-16</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
<Login/>
      <footer>
          Powered by Elyes + Racem + Slim + Ghassen
      </footer>
    </div>
  )
}
